version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true   # remove old images
      - WATCHTOWER_POLL_INTERVAL=10800  # check every 3 hours  

volumes:
  portainer_data:

networks:
  traefik:
    external: true
